language: ruby
rvm:
  - 2.2

install: gem install jekyll html-proofer jekyll-sitemap
script: scripts/build.sh

# branch whitelist
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
