sudo: required
language: ruby
rvm:
  - 2.2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
#  - gem install html-proofer
  - gem install jekyll-sitemap
  - gem install emoji_for_jekyll
script:
  - jekyll build
#  - htmlproofer ./_site
