sudo: required
language: ruby
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install emoji_for_jekyll
  - gem install pygments.rb
script:
  - jekyll build
