sudo: required
language: ruby
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install emoji_for_jekyll
  - gem install pygments.rb


# https://jamiemagee.co.uk/2015/03/31/continuous-deployment-jekyll-to-azure/
script: jekyll build --config _config.yml
after_success:
  deploy:
    provider: azure_web_apps
    username: AZURE_WA_USERNAME
    password: AZURE_WA_PASSWORD
    site: AZURE_WA_SITE
