language: ruby
rvm:
  - 2.2.2
sudo: required
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
  - gem install html-proofer
  - gem install jekyll-sitemap
script:
  - jekyll build
  - htmlproofer _site
