language: ruby
rvm:
  - 2.3.1

install:
  - bundle install
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install emoji_for_jekyll

# https://jamiemagee.co.uk/2015/03/31/continuous-deployment-jekyll-to-azure/
script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh

after_success:
  - chmod +x _scripts/deploy.sh
  - _scripts/deploy.sh

branches:
  only:
    - master

sudo: false
addons:
  apt:
    packages:
      - ncftp

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production


notifications:
  email:
    recipients:
      - ajaykarwal@gmail.com
    on_success: always
    on_failure: always

