###### Site settings
title: Ajay Karwal
metatitle: User Interface Design and Development Portfolio
email: ajaykarwal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    User interface design and development
    portfolio for Ajay Karwal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ajaykarwal.com" # the base hostname & protocol for your site

google_analytics: UA-16609747-8

twitter_username: ajaykarwal
facebook_username: ajaykarwal
dribbble_username: ajaykarwal
linkedin_username: ajaykarwal
behance_username: ajaykarwal
github_username:  ajaykarwal

disqus_shortname: ajaykarwal

###### Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
