###### Site settings
title             : Ajay Karwal
metatitle         : User Interface Design and Development Portfolio
description       : User interface design and development portfolio for Ajay Karwal
tagline           : User interface design and development portfolio for Ajay Karwal
email             : ajaykarwal@gmail.com
base_url          : http://ajaykarwal.com
encoding          : utf-8

author:
  name           : Ajay Karwal
  email          : ajaykarwal@gmail.com

google_analytics  : UA-16609747-8

# Social accounts
twitter_username  : ajaykarwal
facebook_username : ajaykarwal
dribbble_username : ajaykarwal
linkedin_username : ajaykarwal
behance_username  : ajaykarwal
github_username   : ajaykarwal
disqus_shortname  : ajaykarwal

feed_artwork   : /images/feed-artwork.png
  
# Add _pages directory to jekyll build
include: ["_pages"]

exclude:
 - Gemfile
 - Gemfile.lock
 - README.md

#Build settings
permalink: /:title/
sass:
  style: compressed


#Collections
collections:
  books:
    output: true
    permalink: /:path/

future: false

