###### Site settings
title             : Ajay Karwal
metatitle         : Front-end Developer and UI Designer from Buckingham, UK.
description       : Front-end Developer and UI Designer from Buckingham, UK.
tagline           : Front-end Developer and UI Designer from Buckingham, UK.
email             : ajaykarwal@gmail.com
base_url          : https://ajaykarwal.com
encoding          : utf-8

author:
  name           : Ajay Karwal
  email          : ajaykarwal@gmail.com

google_analytics  : UA-16609747-8

disqus_shortname  : ajaykarwal
twitter  : ajaykarwal

feed_artwork   : /images/feed-artwork.png
  
# Add _pages directory to jekyll build
include: ["_pages"]

plugins: ["emoji_for_jekyll"]

exclude:
 - Gemfile
 - Gemfile.lock
 - README.md
 - vendor

#Build settings
permalink: /:title/
sass:
  style: compressed


#Collections
collections:
  books:
    output: true
    permalink: /:path/

future: false

